version: '3.9'

services:
  # WEB APP
  webapp:
    container_name: tourabi-net
    build: .
    ports:
      - 8511:3001
    environment:
      NODE_ENV: production
      HTTP_PORT: 3001
    # API_URI: https://api.tourabi.net/api/v1

# volumes:
